### ISSUE TITLE
No CSS showing

### ISSUE THREAD

**Issue by GrumpyCrouton** [kabachello/jQuery.NumPad#5]
I've got it to where the input pops up, but there is no css showing.

```
<link href="./assets/css/jquery.numpad.css" rel="stylesheet">
<script src="./assets/js/jquery.numpad.js"></script>

<input type="text" id="userID" name="userID" class="form-control nmpd-target"/>

        <script type="text/javascript">
            // Initialize the numpad
            $('#userID').numpad();
        </script>
```

http://prntscr.com/clw60x

**Comment by kabachello** [comment]
Hi! This is the correct behavior if you do not specify any custom CSS. The numpad does not have any own styling by default because I want it to be easily stylable to suite any front-end framework. You can see how to do this in the examples for bootstrap and jquery mobile (look into the demos folder).

The main idea ist to add custom templates for the html-elements used in the numpad. See templating options under parameters on this page: http://a.kabachnik.info/jquery-numpad.html.
